#!/bin/bash

#=======================#
# Global envs           #
#=======================#
export ZINC_FIRST_ADMIN_USER=${DEFAULT_ADMIN_USERNAME:-"admin"}
export ZINC_FIRST_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD:-"pass4Zinc"}
export GIN_MODE=${GIN_MODE:-"release"}

# ======================#
# Persistence directory #
#=======================#
export PHP_PERSISTENCE_LIST=(
"/data")